name: actions-example
on:
  push:
jobs:
  user-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.8.0"
      - name: Install repo dependencies
        run: "npm install"
      - name: Run script from repo
        run: "node helloWorld.js"

