name: Event Triggers Example
on:
  push:
    branches:
      - "develop"
      - "foo/*"
      - "foo/**"
      - "!foo/*/456"
    tags:
      - "*"
  pull_request:
    branches:
      - "develop"
  schedules:
    - cron "*/15 * * * *"
jobs:
  say-hello:
    runs-on: ubuntu_latest
    steps:
      - name: Event
        run: echo "Triggered by: $GITHUB_EVENT_NAME"
      - name: Say Hello
        run: echo "Hello World!"