name: Hello world composite action
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./hello-world-composite-action
        with:
          who-to-greet: "Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash