# Example using a public action
# name: Hello world javascript action
# on: [push]
# jobs:
#   hello_world_job:
#     name: A job to say hello
#     runs-on: ubuntu-latest
#     steps:
#       - name: Hello world action step
#         id: hello
#         uses: actions/hello-world-javascript-action@v1.1
#         with:
#           who-to-greet: 'Octocat'
#       - name: Get the output time
#         run: echo "The time is ${{ steps.hello.outputs.time }}"

# Example using a private action
name: Hello world javascript action
on: [push]
jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: ./hello-world-javascript-action
        with:
          who-to-greet: 'Octocat'
      - name: Get the output time
        run: echo "The time is ${{ steps.hello.outputs.time }}"